### PR TITLE
Enforce stock max en 0 min for amount of products in orders

### LINKED ISSUE #48: Wrong total price
When adding a negative amount of items the total price decreases rendering it inaccurate

### PR DESCRIPTION
**Pull request by VandorpeDavid**
Fixes #48

### CODE REVIEW

File: app/assets/javascripts/orders.js.coffee [hunk 1]
```diff
@@ -9,16 +9,36 @@ ready = ->
...
+      updateInput(row)
+    )
   )
 
   recalculate()
 
+
+
+# Validate input, and then update
+updateInput = (row, useRecalculate = true)->
```
Comment (Silox) [inline app/assets/javascripts/orders.js.coffee]: space before ->

File: app/assets/javascripts/orders.js.coffee [hunk 2]
```diff
@@ -29,12 +49,12 @@ increment = (button, n) ->
 
   # Fix the counter
   counter = $(row).find('.row_counter')
-  counter.val(parseInt(counter.val()) + n)
-
-  # Disable buttons if necessary
-  disIfNec(row)
+  value = parseInt(counter.val())
+  # Apparently CoffeeScript doesn't support ?:
```
Comment (Silox) [inline app/assets/javascripts/orders.js.coffee]: Indeed, no need to comment this though

File: app/assets/javascripts/orders.js.coffee [hunk 3]
```diff
@@ -29,12 +49,12 @@ increment = (button, n) ->
...
+  value =  if isNaN(value) then 0 else value
```
Comment (Silox) [inline app/assets/javascripts/orders.js.coffee]: why not just 
```
if isNan(value)
  value = 0
```

File: app/views/order_items/_order_item.html.erb [hunk 4]
```diff
@@ -9,7 +9,7 @@
         <%= content_tag :span, product.name %>
         <%= content_tag :small, euro(product.price) %>
         </h4>
-        <%= f.counter :count, max: 1000, skip_label: true, wrapper_class: "input-group", class: "row_counter" %>
+        <%= f.counter :count, max: product.stock, min:0, skip_label: true, wrapper_class: "input-group", class: "row_counter" %>
```
Comment (Silox) [inline app/views/order_items/_order_item.html.erb]: space between `min:` and `0`

Comment (Silox) [inline app/views/order_items/_order_item.html.erb]: perhaps swap min and max for readibility?
