### PR TITLE
Fix public transactions api format

### LINKED ISSUE #109: Fix public API
Seems like the render json doesn't take arguments anymore, or needs a specific kwarg

### PR DESCRIPTION
**Pull request by TomNaessens**
Fixes #109

### CODE REVIEW

File: app/controllers/transactions_controller.rb [hunk 1]
```diff
@@ -2,22 +2,23 @@ class TransactionsController < ApplicationController
...
-            id: t.id,
-            debtor: t.debtor.name,
-            creditor: t.creditor.name,
-            time: t.updated_at,
-            amount: t.amount,
-            message: t.message,
-            issuer: t.issuer.name
-          }
-        end
+    transactions = @user.transactions.includes(:debtor, :creditor, :issuer)
```
Comment (chvp) [inline app/controllers/transactions_controller.rb:5]: Are you dure removing the `@` doesn't break the HTML views?

Comment (TomNaessens) [reply app/controllers/transactions_controller.rb:5]: I don't think there are any html views. The transactions list on the index uses the `pages_controller`, and the transaction page uses the datatables endpoint.

**Review by niknetniko — APPROVED** [review]
